export const LANGUAGES = [
  { code: "ar", native: "العربية", english: "Arabic", flag: "🇮🇶", rtl: true },
  { code: "fa-AF", native: "دری", english: "Dari", flag: "🇦🇫", rtl: true },
  { code: "ps", native: "پښتو", english: "Pashto", flag: "🇦🇫", rtl: true },
  { code: "ti", native: "ትግርኛ", english: "Tigrinya", flag: "🇪🇷", rtl: false },
  { code: "so", native: "Soomaali", english: "Somali", flag: "🇸🇴", rtl: false },
  { code: "uk", native: "Українська", english: "Ukrainian", flag: "🇺🇦", rtl: false },
  { code: "es", native: "Español", english: "Spanish", flag: "🇪🇸", rtl: false },
  { code: "sw", native: "Kiswahili", english: "Swahili", flag: "🇰🇪", rtl: false },
  { code: "ta", native: "தமிழ்", english: "Tamil", flag: "🇮🇳", rtl: false },
  { code: "fr", native: "Français", english: "French", flag: "🇨🇦", rtl: false },
  { code: "en", native: "English", english: "English", flag: "🇨🇦", rtl: false },
];

export const CHECKLIST_ITEMS = [
  {
    id: 1,
    phase: "today",
    phaseAr: "اليوم",
    phaseEn: "Today",
    titleAr: "تأكيد تغطية IFHP الصحية",
    titleEn: "Confirm IFHP Health Coverage",
    badge: "today",
    who: "everyone",
    address: "Received at port of entry (Ottawa airport)",
    phone: "1-888-614-1880",
    hours: "N/A — issued on arrival",
    documents: ["COPR", "Passport"],
    qrMessage: "I have IFHP coverage. My IFHP document number is [number]. I need medical assistance and I speak [language].",
    hasQR: true,
    mapQuery: null,
  },
  {
    id: 2,
    phase: "today",
    phaseAr: "اليوم",
    phaseEn: "Today",
    titleAr: "التقديم على رقم التأمين الاجتماعي",
    titleEn: "Apply for SIN Number",
    badge: "today",
    who: "every_adult",
    address: "Service Canada Centre, 360 Albert St, Ottawa ON K1R 7X7",
    phone: "1-866-274-6627",
    hours: "Mon–Fri 8:30 AM – 4:00 PM",
    documents: ["COPR", "Passport or travel document"],
    qrMessage: "My name is [name]. I am a government-assisted refugee and I cannot speak English. I am here to apply for my Social Insurance Number. I speak [language] — please connect me with someone who can help.",
    hasQR: true,
    mapQuery: "Service+Canada+360+Albert+St+Ottawa",
  },
  {
    id: 3,
    phase: "week",
    phaseAr: "هذا الأسبوع",
    phaseEn: "This Week",
    titleAr: "التقديم على بطاقة الصحة",
    titleEn: "OHIP — Apply for Health Card",
    badge: "week",
    who: "everyone",
    address: "ServiceOntario, 110 Laurier Ave W, Ottawa ON K1P 1J1",
    phone: "613-688-4884",
    hours: "Mon–Fri 9:00 AM – 5:00 PM",
    documents: ["COPR", "Passport", "Proof of Ontario address", "Health Card application form"],
    qrMessage: "My name is [name]. I am a government-assisted refugee and I cannot speak English. I am here to apply for my Ontario health card (OHIP). I speak [language].",
    hasQR: true,
    mapQuery: "ServiceOntario+110+Laurier+Ave+W+Ottawa",
  },
  {
    id: 4,
    phase: "week",
    phaseAr: "هذا الأسبوع",
    phaseEn: "This Week",
    titleAr: "فتح حساب بنكي كندي",
    titleEn: "Open Bank Account",
    badge: "week",
    who: "primary_adult",
    address: "TD Bank, 1547 Merivale Rd / RBC, 90 Sparks St / CIBC, 1495 Bank St",
    phone: "TD: 613-729-6161 / RBC: 613-564-8705",
    hours: "Mon–Fri 9:30 AM – 5:00 PM",
    documents: ["Passport", "COPR", "Proof of address (if available)", "SIN (if obtained)"],
    qrMessage: "My name is [name]. I am a recently arrived refugee. I would like to open a newcomer bank account. I speak [language].",
    hasQR: true,
    mapQuery: "TD+Bank+newcomer+Ottawa",
  },
  {
    id: 5,
    phase: "week",
    phaseAr: "هذا الأسبوع",
    phaseEn: "This Week",
    titleAr: "تقييم احتياجات RAP — وكالة التوطين",
    titleEn: "RAP Needs Assessment — Settlement Agency",
    badge: "week",
    who: "family_unit",
    address: "OCISO, 959 Wellington St W / CCI Ottawa, 219 Argyle Ave",
    phone: "OCISO: 613-725-0202 / CCI: 613-232-9634",
    hours: "Mon–Fri 9:00 AM – 5:00 PM",
    documents: ["COPR", "Passport", "IFHP document", "All family members' documents"],
    qrMessage: "My name is [name]. I am a government-assisted refugee. I am here for my initial settlement needs assessment. I speak [language].",
    hasQR: true,
    mapQuery: "OCISO+959+Wellington+St+W+Ottawa",
  },
  {
    id: 6,
    phase: "week",
    phaseAr: "هذا الأسبوع",
    phaseEn: "This Week",
    titleAr: "شراء شريحة هاتف",
    titleEn: "Get Phone / SIM Card",
    badge: "week",
    who: "primary_adult",
    address: "Freedom Mobile, 2269 Riverside Dr / Fido, Rideau Centre",
    phone: "Freedom: 613-424-5503",
    hours: "Mon–Sat 10 AM – 9 PM, Sun 11 AM – 6 PM",
    documents: ["Passport or government ID", "Canadian address"],
    qrMessage: null,
    hasQR: false,
    mapQuery: "Freedom+Mobile+Ottawa",
  },
  {
    id: 7,
    phase: "month",
    phaseAr: "هذا الشهر",
    phaseEn: "This Month",
    titleAr: "تسجيل الأطفال في المدرسة",
    titleEn: "Register Children for School",
    badge: "month",
    who: "kids",
    address: "OCDSB, 133 Greenbank Rd / OCSB, 570 West Hunt Club Rd",
    phone: "OCDSB: 613-596-8211 / OCSB: 613-224-2222",
    hours: "Mon–Fri 8:30 AM – 4:30 PM",
    documents: ["COPR", "Passport", "Immunization records", "Prior transcripts", "Proof of address"],
    qrMessage: "My name is [name]. I am here to enroll my child/children in school. We are government-assisted refugees. I speak [language].",
    hasQR: true,
    mapQuery: "OCDSB+133+Greenbank+Rd+Ottawa",
  },
  {
    id: 8,
    phase: "month",
    phaseAr: "هذا الشهر",
    phaseEn: "This Month",
    titleAr: "البحث عن سكن دائم",
    titleEn: "Find Permanent Housing",
    badge: "month",
    who: "family_unit",
    address: "Ottawa Community Housing, 39 Auriga Dr",
    phone: "OCH: 613-564-1909",
    hours: "Mon–Fri 8:30 AM – 4:30 PM",
    documents: ["Proof of income (RAP letter)", "ID", "References"],
    qrMessage: "My name is [name]. I am a government-assisted refugee looking for permanent housing. I speak [language].",
    hasQR: true,
    mapQuery: "Ottawa+Community+Housing+39+Auriga+Dr",
  },
  {
    id: 9,
    phase: "month",
    phaseAr: "هذا الشهر",
    phaseEn: "This Month",
    titleAr: "تسجيل الحضانة",
    titleEn: "Childcare Registration",
    badge: "month",
    who: "kids_under_6",
    address: "City of Ottawa Child Care Registry — online or call 3-1-1",
    phone: "3-1-1 or 613-580-2400",
    hours: "Mon–Fri 8 AM – 6 PM",
    documents: ["Child's birth certificate or COPR", "Proof of address", "Income information"],
    qrMessage: null,
    hasQR: false,
    mapQuery: null,
  },
  {
    id: 10,
    phase: "month",
    phaseAr: "هذا الشهر",
    phaseEn: "This Month",
    titleAr: "التقييم اللغوي وتسجيل LINC",
    titleEn: "Language Assessment & LINC Enrollment",
    badge: "month",
    who: "adults_needing_language",
    address: "YMCA-YWCA Language Assessment Centre, 180 Argyle Ave",
    phone: "613-237-1320 ext 260",
    hours: "Mon–Fri 8:30 AM – 4:00 PM",
    documents: ["COPR", "Passport or PR card"],
    qrMessage: "My name is [name]. I am here for my language assessment for LINC classes. I am a refugee and I speak [language].",
    hasQR: true,
    mapQuery: "YMCA+180+Argyle+Ave+Ottawa",
  },
  {
    id: 11,
    phase: "month",
    phaseAr: "هذا الشهر",
    phaseEn: "This Month",
    titleAr: "التقديم على إعانة الطفل الكندية",
    titleEn: "Apply for Canada Child Benefit (CCB)",
    badge: "month",
    who: "kids",
    address: "Apply online via CRA My Account or mail RC66 form",
    phone: "CRA: 1-800-387-1193",
    hours: "Mon–Fri 9 AM – 5 PM (phone)",
    documents: ["SIN (all adults)", "Child's birth certificate", "COPR", "Proof of address", "RC66 and RC66SCH forms"],
    qrMessage: null,
    hasQR: false,
    mapQuery: null,
  },
  {
    id: 12,
    phase: "month",
    phaseAr: "هذا الشهر",
    phaseEn: "This Month",
    titleAr: "التسجيل في ائتمان GST/HST",
    titleEn: "GST/HST Credit Registration",
    badge: "month",
    who: "every_adult",
    address: "Apply via RC151 form mailed to CRA",
    phone: "CRA: 1-800-387-1193",
    hours: "Mon–Fri 9 AM – 5 PM (phone)",
    documents: ["SIN", "Completed RC151 form"],
    qrMessage: null,
    hasQR: false,
    mapQuery: null,
  },
  {
    id: 13,
    phase: "month",
    phaseAr: "هذا الشهر",
    phaseEn: "This Month",
    titleAr: "تطعيمات وسجلات التلقيح",
    titleEn: "Immunization Records / Catch-up Vaccines",
    badge: "month",
    who: "everyone",
    address: "Ottawa Public Health, 100 Constellation Dr",
    phone: "613-580-6744",
    hours: "Mon–Fri 8:30 AM – 4:30 PM",
    documents: ["Passport", "Existing immunization records", "OHIP or IFHP card"],
    qrMessage: "My name is [name]. I need to update my immunization records. I am a refugee and I speak [language].",
    hasQR: true,
    mapQuery: "Ottawa+Public+Health+100+Constellation+Dr",
  },
  {
    id: 14,
    phase: "month",
    phaseAr: "هذا الشهر",
    phaseEn: "This Month",
    titleAr: "دعم الإعاقة — ODSP",
    titleEn: "ODSP — Disability Support Program",
    badge: "month",
    who: "disability",
    address: "ODSP Ottawa, 351 Preston St, 2nd Floor",
    phone: "613-787-3951",
    hours: "Mon–Fri 8:30 AM – 5:00 PM",
    documents: ["Medical documentation", "COPR", "Proof of address", "Income information"],
    qrMessage: "My name is [name]. I am a government-assisted refugee with a disability. I am here to apply for the Ontario Disability Support Program. I speak [language].",
    hasQR: true,
    mapQuery: "ODSP+351+Preston+St+Ottawa",
  },
  {
    id: 15,
    phase: "month",
    phaseAr: "هذا الشهر",
    phaseEn: "This Month",
    titleAr: "خدمات كبار السن",
    titleEn: "Senior-Specific Services",
    badge: "month",
    who: "seniors",
    address: "Service Canada, 360 Albert St / Ottawa Council on Aging, 411 MacLaren St",
    phone: "1-866-274-6627 / OCA: 613-789-3577",
    hours: "Mon–Fri 8:30 AM – 4:30 PM",
    documents: ["COPR", "Passport", "Proof of age"],
    qrMessage: "My name is [name]. I am a senior refugee. I am here to inquire about services for seniors. I speak [language].",
    hasQR: true,
    mapQuery: "Ottawa+Council+on+Aging+411+MacLaren+St",
  },
  {
    id: 16,
    phase: "3months",
    phaseAr: "٣ أشهر",
    phaseEn: "Months 2–3",
    titleAr: "تأكيد عنوان بطاقة الإقامة الدائمة",
    titleEn: "PR Card — Confirm Address with IRCC",
    badge: "3month",
    who: "every_pr",
    address: "Online via IRCC web portal",
    phone: "IRCC: 1-888-242-2100",
    hours: "Mon–Fri 8 AM – 4 PM (phone)",
    documents: ["COPR", "Canadian mailing address"],
    qrMessage: null,
    hasQR: false,
    mapQuery: null,
  },
  {
    id: 17,
    phase: "3months",
    phaseAr: "٣ أشهر",
    phaseEn: "Months 2–3",
    titleAr: "رخصة القيادة",
    titleEn: "Driver's License",
    badge: "3month",
    who: "adults_who_drive",
    address: "DriveTest Centre, 1500 St Laurent Blvd",
    phone: "647-776-0022",
    hours: "Mon–Fri 8:30 AM – 5:00 PM, Sat 8:30 AM – 1:00 PM",
    documents: ["COPR or PR card", "Foreign driver's license", "Proof of address", "OHIP card"],
    qrMessage: "My name is [name]. I am a refugee and I am here to begin my driver's license process. I speak [language].",
    hasQR: true,
    mapQuery: "DriveTest+1500+St+Laurent+Blvd+Ottawa",
  },
  {
    id: 18,
    phase: "3months",
    phaseAr: "٣ أشهر",
    phaseEn: "Months 2–3",
    titleAr: "الاستعداد للعمل والاعتراف بالمؤهلات",
    titleEn: "Job Readiness / Credential Recognition",
    badge: "3month",
    who: "working_age",
    address: "OCISO Employment Services, 959 Wellington St W",
    phone: "OCISO: 613-725-0202",
    hours: "Mon–Fri 9 AM – 5 PM",
    documents: ["Resume", "Educational transcripts", "COPR", "Professional certificates"],
    qrMessage: "My name is [name]. I am a refugee looking for employment support. I speak [language].",
    hasQR: true,
    mapQuery: "OCISO+959+Wellington+St+Ottawa",
  },
];

export const PROGRAMS = [
  {
    id: "opl",
    name: "Ottawa Public Library — Newcomer Services",
    description: "Free library card, internet, printing, ESL conversation circles, settlement workers at select branches.",
    address: "120 Metcalfe St, Ottawa",
    phone: "613-580-2940",
    filter: "all",
    mapQuery: "Ottawa+Public+Library+120+Metcalfe+St",
  },
  {
    id: "ociso",
    name: "OCISO Community Connections",
    description: "Social activities, cultural orientation, mentorship matching, community kitchen programs.",
    address: "959 Wellington St W, Ottawa",
    phone: "613-725-0202",
    filter: "all",
    mapQuery: "OCISO+959+Wellington+St+Ottawa",
  },
  {
    id: "cci",
    name: "CCI Ottawa Community Programs",
    description: "Homework clubs, women's groups, conversation circles, digital literacy workshops, cooking programs.",
    address: "219 Argyle Ave, Ottawa",
    phone: "613-232-9634",
    filter: "all",
    mapQuery: "CCI+219+Argyle+Ave+Ottawa",
  },
  {
    id: "211",
    name: "211 Ontario Helpline",
    description: "Free helpline connecting people to social services — housing, food, mental health, legal aid. Multilingual.",
    address: "Phone service — dial 2-1-1",
    phone: "2-1-1 or 1-877-330-3213",
    filter: "all",
    mapQuery: null,
  },
  {
    id: "chc",
    name: "Somerset West Community Health Centre",
    description: "Primary care for uninsured and underinsured patients, mental health counselling, prenatal care.",
    address: "55 Eccles St, Ottawa",
    phone: "613-238-8210",
    filter: "all",
    mapQuery: "Somerset+West+Community+Health+Centre+Ottawa",
  },
  {
    id: "hand",
    name: "Hand in Hand Recreation Subsidy",
    description: "$185/person/year subsidy for recreation programs and memberships for low-income residents.",
    address: "Apply online or at any City recreation facility",
    phone: "3-1-1 or 613-580-2400",
    filter: "all",
    mapQuery: null,
  },
  {
    id: "transit",
    name: "OC Transpo — Community Pass",
    description: "Reduced-fare transit pass ($70.75/month) for Ontario Works and ODSP recipients.",
    address: "OC Transpo Customer Service, Rideau Centre, 2nd Floor",
    phone: "613-741-4390",
    filter: "all",
    mapQuery: "OC+Transpo+Rideau+Centre+Ottawa",
  },
  {
    id: "earlyyears",
    name: "Ontario Early Years Centres",
    description: "Free drop-in programs for children 0–6 and parents — play, learning, parenting workshops.",
    address: "Multiple locations across Ottawa",
    phone: "613-727-4723",
    filter: "kids",
    mapQuery: "EarlyON+Child+Family+Centre+Ottawa",
  },
  {
    id: "bgc",
    name: "Boys and Girls Club of Ottawa",
    description: "Free after-school programs, homework help, sports, arts, leadership for kids 6–18.",
    address: "531 Tremblay Rd, Ottawa",
    phone: "613-563-1660",
    filter: "kids",
    mapQuery: "Boys+Girls+Club+531+Tremblay+Ottawa",
  },
  {
    id: "mlo",
    name: "OCISO Multicultural Liaison Officers",
    description: "Settlement workers in Ottawa schools helping newcomer families navigate registration and school culture.",
    address: "In schools — coordinated through OCDSB and OCSB",
    phone: "613-725-0202",
    filter: "kids",
    mapQuery: null,
  },
  {
    id: "daycare",
    name: "$10/Day Childcare Program",
    description: "Subsidized childcare under Ontario's Canada-Wide Early Learning and Child Care program.",
    address: "Apply via City of Ottawa Child Care Registry",
    phone: "3-1-1 or 613-580-2400",
    filter: "kids",
    mapQuery: null,
  },
  {
    id: "oca",
    name: "Ottawa Council on Aging",
    description: "Information hub for senior services, Age-Friendly Ottawa initiatives, social programming.",
    address: "411 MacLaren St #200, Ottawa",
    phone: "613-789-3577",
    filter: "seniors",
    mapQuery: "Ottawa+Council+on+Aging+411+MacLaren",
  },
  {
    id: "gc",
    name: "Good Companions Seniors' Centre",
    description: "Drop-in meals, social programs, exercise classes, day programs, transportation assistance.",
    address: "670 Albert St, Ottawa",
    phone: "613-236-0428",
    filter: "seniors",
    mapQuery: "Good+Companions+670+Albert+St+Ottawa",
  },
  {
    id: "mow",
    name: "Meals on Wheels Ottawa",
    description: "Hot meal delivery for homebound seniors and people with disabilities.",
    address: "Citywide delivery",
    phone: "613-233-2424",
    filter: "seniors",
    mapQuery: null,
  },
  {
    id: "odsp",
    name: "ODSP — Ontario Disability Support Program",
    description: "Monthly income support (up to $1,436/single) and extended health benefits.",
    address: "351 Preston St, 2nd Floor, Ottawa",
    phone: "613-787-3951",
    filter: "disability",
    mapQuery: "ODSP+351+Preston+St+Ottawa",
  },
  {
    id: "adp",
    name: "Assistive Devices Program (ADP)",
    description: "Covers 75% of cost of wheelchairs, hearing aids, prosthetics, communication devices.",
    address: "Through prescribing physician",
    phone: "1-800-268-6021",
    filter: "disability",
    mapQuery: null,
  },
  {
    id: "inclrec",
    name: "City of Ottawa Inclusive Recreation",
    description: "Adapted recreation programs, 1-on-1 support, specialized camps, para-sport.",
    address: "Apply via registerottawa.ca",
    phone: "613-580-2424 ext 31217",
    filter: "disability",
    mapQuery: null,
  },
];

export const BADGE_STYLES = {
  today: { background: "#FEE2E2", color: "#991B1B" },
  week: { background: "#FEF3C7", color: "#92400E" },
  month: { background: "#DBEAFE", color: "#1E40AF" },
  "3month": { background: "#E0E7FF", color: "#3730A3" },
  "6month": { background: "#F1F4F6", color: "#4A5568" },
};
